image:
  file: .gitpod.Dockerfile

ports:
  - port: 19000-19006
    onOpen: notify
    visibility: public
    description: Expo Metro Bundler
  - port: 8081
    onOpen: notify
    visibility: public
    description: React Native Metro
  - port: 3000
    onOpen: notify
    visibility: public
    description: React Development Server
  - port: 8080
    visibility: public
    onOpen: ignore
    description: Backend API Server
  - port: 8082
    visibility: public
    onOpen: open-browser
    description: Frontend Dashboard

tasks:
  - name: Setup Expo Build Environment
    init: |
      # Update system
      sudo apt-get update
      sudo apt-get install -y curl git wget gnupg lsb-release jq unzip
      
      # Install Node.js 18
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      
      # Install AWS CLI (for S3 uploads)
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf aws awscliv2.zip
      
      # Install Expo and EAS CLI
      npm install -g eas-cli expo-cli
      
      # Install project dependencies
      cd /workspace/africa-railways
      npm ci || npm install
      
      # Install backend dependencies
      cd backend && go mod download || true
      
      # Install mobile dependencies
      cd /workspace/africa-railways/SmartphoneApp && npm install --legacy-peer-deps || true
      
      # Create necessary directories
      mkdir -p ~/.aws ~/.expo builds
      
      # Make scripts executable
      cd /workspace/africa-railways
      chmod +x scripts/*.sh || true
      
      echo "✅ Dependencies installed"
      
    command: |
      cd /workspace/africa-railways
      echo "🚀 Expo Build Environment Ready!"
      echo "=================================================="
      echo ""
      echo "📋 Available Commands:"
      echo "  • ./scripts/deploy-build.sh     - Build & deploy to S3"
      echo "  • ./scripts/setup-s3-gitpod.sh  - Setup AWS S3 for builds"
      echo "  • npm start                     - Start Expo dev server"
      echo "  • eas login                     - Login to Expo"
      echo "  • make eas-build                - Interactive build menu"
      echo ""
      echo "🔧 Setup:"
      echo "  1. Run: eas login (or set EXPO_TOKEN)"
      echo "  2. Run: ./scripts/setup-env.sh (configure credentials)"
      echo "  3. Run: ./scripts/deploy-build.sh (build & deploy)"
      echo ""
      echo "📱 Current Status:"
      echo "  • Node.js: $(node --version 2>/dev/null || echo 'Not found')"
      echo "  • EAS CLI: $(eas --version 2>/dev/null || echo 'Not found')"
      echo "  • AWS CLI: $(aws --version 2>&1 | head -n 1 || echo 'Not found')"
      echo ""
      echo "📚 Documentation:"
      echo "  • README-Gitpod.md              - Gitpod guide"
      echo "  • EAS_BUILD_SETUP.md            - Build guide"
      echo "  • BUILD_STATUS.md               - Current build status"
      echo "  • DOWNLOAD_PAGE_SETUP.md        - Download page setup"
      echo ""
      
      # Open README if it exists
      if [ -f "README-Gitpod.md" ]; then
        gp open README-Gitpod.md
      fi

vscode:
  extensions:
    - msjsdiag.vscode-react-native
    - byCedric.vscode-expo
    - AmazonWebServices.aws-toolkit-vscode
    - golang.go
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addBadge: true
