tasks:
  - name: Setup and Services
    init: |
      # Install dependencies during prebuild (cached)
      cd /workspace/africa-railways
      cd backend && go mod download || true
      cd /workspace/africa-railways/mobile && npm install || true
      cd /workspace/africa-railways
      echo "✅ Dependencies installed"
      
    command: |
      echo "🚀 Ready to build!"
      echo ""
      echo "Available commands:"
      echo "  make help    - Show all commands"
      echo "  make test    - Run tests"
      echo "  make dev     - Start development servers"
      echo ""
      # Don't put 'go build' or 'eas build' here 
      # unless you want them to run every single time you open the tab.

ports:
  - port: 8080
    visibility: public
    onOpen: ignore
  - port: 8082
    visibility: public
    onOpen: open-browser
  - port: 3000
    visibility: public
    onOpen: ignore
