tasks:
  - name: Setup and Services
    init: |
      sudo apt update && sudo apt install -y golang-go
      chmod +x check-services.sh
    command: |
      # 1. Start Backend Engine
      cd backend && nohup go run main.go > engine.log 2>&1 &
      cd ..
      
      # 2. Start Python Servers
      nohup python3 -m http.server 8082 --directory . > server8082.log 2>&1 &
      nohup python3 -m http.server 3000 --directory . > server3000.log 2>&1 &
      
      # 3. Final Status Check
      sleep 3
      ./check-services.sh

ports:
  - port: 8080
    visibility: public
    onOpen: ignore
  - port: 8082
    visibility: public
    onOpen: open-browser
  - port: 3000
    visibility: public
    onOpen: ignore
