image:
  file: .gitpod.Dockerfile

ports:
  - port: 19000-19006
    onOpen: notify
    visibility: public
    description: Expo Metro Bundler
  - port: 8081
    onOpen: notify
    visibility: public
    description: React Native Metro
  - port: 3000
    onOpen: notify
    visibility: public
    description: React Development Server
  - port: 8080
    visibility: public
    onOpen: ignore
    description: Backend API Server
  - port: 8082
    visibility: public
    onOpen: open-browser
    description: Frontend Dashboard

tasks:
  - name: Setup Environment
    init: |
      # Install project dependencies
      cd /workspace/africa-railways
      npm ci || npm install
      
      # Install backend dependencies
      cd backend && go mod download || true
      
      # Install mobile dependencies
      cd /workspace/africa-railways/mobile && npm install || true
      
      # Create necessary directories
      mkdir -p ~/.aws ~/.expo builds
      
      # Make scripts executable
      chmod +x scripts/*.sh || true
      
      echo "âœ… Dependencies installed"
      
    command: |
      cd /workspace/africa-railways
      source ~/.bashrc
      
      echo "ðŸš€ Africa Railways - Gitpod Development Environment"
      echo "=================================================="
      echo ""
      echo "ðŸ“± Mobile Development Commands:"
      echo "  npm start              - Start Expo dev server"
      echo "  eas login              - Login to Expo account"
      echo "  eas build              - Build app with EAS"
      echo "  make eas-build         - Interactive build menu"
      echo "  make eas-android       - Quick Android build"
      echo ""
      echo "ðŸ› ï¸  Backend Commands:"
      echo "  make dev               - Start all services"
      echo "  make backend           - Start backend only"
      echo "  make status            - Check service status"
      echo ""
      echo "â˜ï¸  AWS/S3 Deployment:"
      echo "  ./scripts/setup-s3.sh      - Setup S3 bucket"
      echo "  ./scripts/deploy-build.sh  - Build and deploy to S3"
      echo ""
      echo "ðŸ“š Documentation:"
      echo "  EAS_BUILD_SETUP.md              - Complete build guide"
      echo "  SELF_HOSTED_RUNNER_SETUP.md     - Self-hosted setup"
      echo "  BUILD_STRATEGY_COMPARISON.md    - Strategy comparison"
      echo "  README-Gitpod.md                - Gitpod-specific guide"
      echo ""
      echo "ðŸ”§ Environment Info:"
      echo "  Node.js: $(node --version)"
      echo "  Java: $(java -version 2>&1 | head -n 1)"
      echo "  Android SDK: ${ANDROID_HOME}"
      echo "  AWS CLI: $(aws --version 2>&1 | head -n 1)"
      echo ""
      echo "ðŸ“‹ Next Steps:"
      echo "  1. Run: eas login"
      echo "  2. Configure AWS credentials (if using S3)"
      echo "  3. Run: make eas-build"
      echo ""
      
      # Open README if it exists
      if [ -f "README-Gitpod.md" ]; then
        gp open README-Gitpod.md
      fi

vscode:
  extensions:
    - msjsdiag.vscode-react-native
    - byCedric.vscode-expo
    - AmazonWebServices.aws-toolkit-vscode
    - golang.go
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addBadge: true
