#!/bin/bash

# 🔐 Secure Secrets Setup Script
# This script helps you set up API keys securely

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🔐 Secure Secrets Setup                                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  IMPORTANT: This script will help you set up secrets securely."
echo "    Your keys will NOT be displayed or logged."
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists."
    read -p "Do you want to overwrite it? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# Create .env file
echo "📝 Creating .env file..."
cat > .env << 'EOF'
# Environment Variables
# Generated by setup-secrets.sh
# DO NOT COMMIT THIS FILE!

# Railways Configuration
RAILWAYS_API_KEY=
RAILWAYS_API_URL=https://africa-railways.vercel.app

# Africoin Configuration
AFRICOIN_API_KEY=
AFRICOIN_API_URL=https://africoin-wallet.vercel.app

# Expo/EAS
EXPO_TOKEN=

# Database
DATABASE_URL=

# Sui Blockchain
SUI_RPC_URL=https://fullnode.mainnet.sui.io:443
EOF

echo "✅ .env file created"
echo ""

# Prompt for keys (hidden input)
echo "📋 Now let's add your API keys..."
echo "   (Your input will be hidden for security)"
echo ""

read -sp "Enter RAILWAYS_API_KEY: " RAILWAYS_KEY
echo ""
read -sp "Enter AFRICOIN_API_KEY: " AFRICOIN_KEY
echo ""
read -sp "Enter EXPO_TOKEN (optional, press Enter to skip): " EXPO_KEY
echo ""

# Update .env file
if [ -n "$RAILWAYS_KEY" ]; then
    sed -i "s|RAILWAYS_API_KEY=|RAILWAYS_API_KEY=$RAILWAYS_KEY|" .env
    echo "✅ Railways API key added"
fi

if [ -n "$AFRICOIN_KEY" ]; then
    sed -i "s|AFRICOIN_API_KEY=|AFRICOIN_API_KEY=$AFRICOIN_KEY|" .env
    echo "✅ Africoin API key added"
fi

if [ -n "$EXPO_KEY" ]; then
    sed -i "s|EXPO_TOKEN=|EXPO_TOKEN=$EXPO_KEY|" .env
    echo "✅ Expo token added"
fi

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ Local Setup Complete!                                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Your .env file has been created with your secrets."
echo ""
echo "⚠️  IMPORTANT:"
echo "   • .env is in .gitignore (won't be committed)"
echo "   • Never share your .env file"
echo "   • Never commit secrets to git"
echo ""

# Offer to set up GitHub secrets
echo "Would you like to set up GitHub Secrets now?"
echo "(Requires GitHub CLI: gh)"
echo ""
read -p "Set up GitHub Secrets? (y/n): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    if command -v gh &> /dev/null; then
        echo ""
        echo "Setting up GitHub Secrets..."
        
        if [ -n "$RAILWAYS_KEY" ]; then
            echo "$RAILWAYS_KEY" | gh secret set RAILWAYS_API_KEY
            echo "✅ RAILWAYS_API_KEY added to GitHub"
        fi
        
        if [ -n "$AFRICOIN_KEY" ]; then
            echo "$AFRICOIN_KEY" | gh secret set AFRICOIN_API_KEY
            echo "✅ AFRICOIN_API_KEY added to GitHub"
        fi
        
        if [ -n "$EXPO_KEY" ]; then
            echo "$EXPO_KEY" | gh secret set EXPO_TOKEN
            echo "✅ EXPO_TOKEN added to GitHub"
        fi
        
        echo ""
        echo "✅ GitHub Secrets configured!"
    else
        echo "❌ GitHub CLI (gh) not found."
        echo "   Install it: https://cli.github.com/"
        echo "   Or add secrets manually: https://github.com/mpolobe/africa-railways/settings/secrets/actions"
    fi
fi

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🎉 Setup Complete!                                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. ✅ Local .env file created"
echo "  2. ⚠️  Add secrets to Vercel (if deploying)"
echo "  3. ⚠️  Add secrets to EAS (if building apps)"
echo ""
echo "For more info, see: SECURITY_GUIDE.md"
echo ""
