run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    check-blank: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - cmd/mint-ticket
    - cmd/mint-ticket-full
    - cmd/mint-sponsored-ticket
    - cmd/invisible-ticket
  exclude-files:
    - ".*_test\\.go$"
